### ISSUE TITLE
Inheritance?

### ISSUE THREAD

**Issue by thgie** [hamlphp/HamlPHP#22]
Thanks for the good work on HamlPHP. I'm using it in conjunction with slim.

Is there any way to have template inheritance, like in Twig? Or what is the best way to share parts of templates?

**Comment by svallory** [comment]
Sorry for the late response! HamlPHP isn't a template engine it's a language parser. @licensetoil forked implemented helpers for rendering partials. I believe that would be the best way to do it. It wasn't merged into HamlPHP because it's not the purpose of the project. Be aware that https://github.com/licensetoil/HamlPHP repository is outdated, but you can look at how he did it and implement it in an updated version.

**Comment by thgie** [comment]
Thanks for the reply svallory. I found just what I needed with MtHaml. It parses haml to php or twig. And twig has inheritance: https://github.com/arnaud-lb/MtHaml
